### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by apcamargo** [adammarples/rocksdbdict#7]
I just discovered this package and it solves some problems I've been facing without a drop in performance as big as SQLite's. It would be cool to have it in [conda-forge](https://github.com/conda-forge/staged-recipes) so other packages can depend on it. :)

**Comment by adammarples** [comment]
Do you know how to do this? Very happy to accept PRs

**Comment by apcamargo** [comment]
I opened a PR [here](https://github.com/conda-forge/staged-recipes/pull/18183). Now they need to accept the package recipe.

Let me know if you want to be a maintainer. It's basically accepting PRs that are automatically created every time conda-forge's bot detects a new version in PyPI.

**Comment by adammarples** [comment]
Sure, great, thanks

**Comment by adammarples** [comment]
@apcamargo the python-rocksdb package itself does have a dependency on rocksdb, will this be handled by conda?

**Comment by apcamargo** [comment]
Done! Should be possible to install with Conda now.

> @apcamargo the python-rocksdb package itself does have a dependency on rocksdb, will this be handled by conda?

Apparently `python-rocksdb`'s Conda package depends on `rocksdb` to build, not for running. But yeah, Conda would handle this sort of dependency graph.

**Comment by adammarples** [comment]
@apcamargo thanks very much!
